### ISSUE TITLE
test/comment thought

### ISSUE THREAD

**Issue by harold** [cnuernber/ham-scripted#1]
https://github.com/cnuernber/ham-scripted/blob/79214b57a96b50595a61d979976fa787397943b1/src/ham_scripted/api.cljs#L80-L83

I don't see the difference between these two lines. Should one of them say `java-hashmap`?

**Comment by cnuernber** [comment]
Yes - one should

**Comment by cnuernber** [comment]
fixed with updated timings

**Comment by harold** [comment]
:+1:
